"use client";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { User, Globe, ShieldCheck, Heart, Award, Mail } from "lucide-react";

export default function AboutPage() {
  return (
    <div style={{ minHeight: "100vh", background: "var(--bg)" }}>
      <Navbar />
      
      <div style={{ paddingTop: "120px", paddingBottom: "100px" }}>
        <div className="container-custom">
          
          {/* Mission Section */}
          <div style={{ textAlign: "center", maxWidth: "800px", margin: "0 auto 80px" }}>
            <span className="badge badge-accent" style={{ marginBottom: "16px" }}>Our Mission</span>
            <h1 style={{ fontSize: "clamp(32px, 5vw, 56px)", color: "var(--primary)", marginBottom: "24px", lineHeight: "1.1" }}>
              Democratizing World-Class Healthcare
            </h1>
            <p style={{ fontSize: "20px", lineHeight: "1.7", color: "var(--text-secondary)" }}>
              MediTrip was founded on a simple belief: your quality of care should not be limited by your zip code. We use AI to bridge the gap between patients and the world's most affordable, high-quality hospitals.
            </p>
          </div>

          {/* Founder Section */}
          <div style={{ 
            background: "white", 
            borderRadius: "32px", 
            padding: "clamp(32px, 6vw, 80px)", 
            border: "1px solid var(--border)", 
            boxShadow: "var(--shadow-lg)",
            display: "grid",
            gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
            gap: "64px",
            alignItems: "center",
            marginBottom: "100px"
          }}>
            <div style={{ position: "relative" }}>
                <img 
                  src="/yug.png" 
                  alt="Yug Rathee" 
                  style={{ width: "100%", height: "100%", objectFit: "cover" }} 
                />
                <div style={{ position: "absolute", bottom: "24px", left: "24px", background: "rgba(255,255,255,0.1)", backdropFilter: "blur(12px)", padding: "12px 20px", borderRadius: "12px", border: "1px solid rgba(255,255,255,0.2)" }}>
                  <span style={{ color: "white", fontWeight: "700", fontSize: "14px" }}>Yug Rathee, Founder</span>
                </div>
            </div>
            <div>
              <span style={{ color: "var(--accent)", fontWeight: "800", textTransform: "uppercase", fontSize: "14px", letterSpacing: "0.1em" }}>Meet the Founder</span>
              <h2 style={{ fontSize: "40px", color: "var(--primary)", marginTop: "12px", marginBottom: "24px" }}>Yug Rathee</h2>
              <p style={{ fontSize: "17px", lineHeight: "1.8", color: "var(--text-secondary)", marginBottom: "20px" }}>
                I started MediTrip after seeing the staggering price differences in global healthcare for the same life-saving procedures. My goal is to empower patients with data, transparency, and choice.
              </p>
              <p style={{ fontSize: "17px", lineHeight: "1.8", color: "var(--text-secondary)", marginBottom: "32px" }}>
                Every report generated by our AI is a step toward a world where healthcare is accessible to everyone, regardless of their financial background.
              </p>
              <div style={{ display: "flex", gap: "16px" }}>
                <a href="mailto:yugrathee28@gmail.com" style={{ textDecoration: "none" }}>
                  <button className="btn-primary" style={{ padding: "12px 24px" }}>
                    <Mail size={16} /> Contact Yug
                  </button>
                </a>
                <a href="https://www.linkedin.com/in/yug-rathee-a1388b333/" target="_blank" rel="noopener noreferrer" style={{ textDecoration: "none" }}>
                  <button style={{ 
                    padding: "12px 24px", 
                    borderRadius: "12px", 
                    border: "1px solid var(--border)", 
                    background: "white", 
                    color: "var(--primary)",
                    fontWeight: "700",
                    display: "flex",
                    alignItems: "center",
                    gap: "8px",
                    cursor: "pointer",
                    transition: "all 0.2s"
                  }} onMouseEnter={(e) => e.currentTarget.style.background = "#f8f9fa"} onMouseLeave={(e) => e.currentTarget.style.background = "white"}>
                    <Globe size={16} color="#0077B5" /> LinkedIn
                  </button>
                </a>
              </div>
            </div>
          </div>

          {/* Stats/Values */}
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(250px, 1fr))", gap: "32px" }}>
            {[
              { icon: Globe, title: "Global Reach", text: "Connecting patients with hospitals in over 40 countries." },
              { icon: ShieldCheck, title: "Verified Quality", text: "Only JCI-accredited and verified clinical facilities." },
              { icon: Heart, title: "Patient First", text: "Neutral, unbiased data to help you make the best choice." }
            ].map((val, i) => (
              <div key={i} className="card" style={{ padding: "32px", textAlign: "center" }}>
                <div style={{ width: "56px", height: "56px", background: "rgba(16,185,129,0.1)", borderRadius: "16px", display: "flex", alignItems: "center", justifyContent: "center", margin: "0 auto 20px" }}>
                  <val.icon size={24} color="var(--accent)" />
                </div>
                <h3 style={{ fontSize: "20px", color: "var(--primary)", marginBottom: "12px" }}>{val.title}</h3>
                <p style={{ color: "var(--text-secondary)", fontSize: "15px", lineHeight: "1.6" }}>{val.text}</p>
              </div>
            ))}
          </div>

        </div>
      </div>

      <Footer />
    </div>
  );
}
